baseURL = "https://everalerta.com"
languageCode = "en-us"
theme = "alerta"
title = "Ever Alerta"
sectionPagesMenu = "navigation"

[params]
    description = "Ever Alerta"


[markup.goldmark.renderer]
    unsafe= true
